PrecisionToolingEF/Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace PrecisionToolingEF.Controllers
{
    public class AdministrationController : Controller
    {
        public IActionResult Index()
        {
            return View("AdminEmployees");
        }

        public IActionResult Employees()
        {
            return View("AdminEmployees");
        }

        public IActionResult Payroll()
        {
            return View();
        }

        public IActionResult Settings()
        {
            return View("AdminSettings");
        }
    }
}

PrecisionToolingEF/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PrecisionToolingEF.Data;
using PrecisionToolingEF.Models;

namespace PrecisionToolingEF.Controllers
{
    public class CustomersController : Controller
    {
        private readonly PrecisionToolingContext _context;

        public CustomersController(PrecisionToolingContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address1,Address2,City,State,ZipCode,Notes,Phone,FaxNumber,Contact")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address1,Address2,City,State,ZipCode,Notes,Phone,FaxNumber,Contact")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            if (customer != null)
            {
                _context.Customers.Remove(customer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }
    }
}

PrecisionToolingEF/Controllers/JobController.cs
using Microsoft.AspNetCore.Mvc;

namespace PrecisionToolingEF.Controllers
{
    public class JobController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult JobGeneral()
        {
            return View();
        }

        public IActionResult Labor()
        {
            return View();
        }

        public IActionResult Material()
        {
            return View();
        }

        public IActionResult EditLabor()
        {
            return View("EditLabor");
        }

        public IActionResult EditMaterial()
        {
            return View("EditMaterialView");
        }

        public IActionResult EditGeneral()
        {
            return View("EditGeneralView");
        }
    }
}

PrecisionToolingEF/Views/Shared/_AdminNavigationView.cshtml
<!--  ADMINISTRATION NAVIGATION -->
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">

        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="nav nav-pills">

                <li class="nav-item">
                    @{
                        if (ViewData["Screen"]?.ToString() == "Employees")
                        {
                            <a class="nav-link active" asp-area="" asp-controller="Administration" asp-action="Employees">Employees</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-area="" asp-controller="Administration" asp-action="Employees">Employees</a>
                        }
                    }

                </li>
                <li class="nav-item">
                    @{
                        if (ViewData["Screen"]?.ToString() == "Payroll")
                        {
                            <a class="nav-link active" asp-area="" asp-controller="Administration" asp-action="Payroll">Payroll</a>
                        }
                        else
                        {
                            <a class="nav-link " asp-area="" asp-controller="Administration" asp-action="Payroll">Payroll</a>
                        }
                    }

                </li>
                <li class="nav-item">
                    @{
                        if (ViewData["Screen"]?.ToString() == "Settings")
                        {
                            <a class="nav-link active" asp-area="" asp-controller="Administration" asp-action="Settings">Settings</a>
                        }
                        else
                        {
                            <a class="nav-link " asp-area="" asp-controller="Administration" asp-action="Settings">Settings</a>
                        }
                    }

                </li>
            </ul>
        </div>
    </div>
</nav>

PrecisionToolingEF/Views/Shared/_AdministrationLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Precision Tooling EF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrecisionToolingEF.styles.css" asp-append-version="true" />
    <title>Precision Tools & Manufacturing Solutions</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">

</head>
<body>
    <partial name="_MainHeader" />

    
    <div class="container">

        <partial name="_AdminNavigationView" />

        @* <!--  ADMINISTRATION NAVIGATION -->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav nav-tabs">

                        <li class="nav-item">
                            @{
                                if (ViewData["Screen"]?.ToString() == "General")
                                {
                                    <a class="nav-link active" asp-area="" asp-controller="Administration" asp-action="Employees">Employees</a>
                                }
                                else
                                {
                                    <a class="nav-link" asp-area="" asp-controller="Administration" asp-action="Employees">Employees</a>
                                }
                            }

                        </li>
                        <li class="nav-item">
                            @{
                                if (ViewData["Screen"]?.ToString() == "Labor")
                                {
                                    <a class="nav-link active" asp-area="" asp-controller="Job" asp-action="Labor">Payroll</a>
                                }
                                else
                                {
                                    <a class="nav-link " asp-area="" asp-controller="Job" asp-action="Labor">Payroll</a>
                                }
                            }

                        </li>
                        <li class="nav-item">
                            @{
                                if (ViewData["Screen"]?.ToString() == "Material")
                                {
                                    <a class="nav-link active" asp-area="" asp-controller="Job" asp-action="Material">Settings</a>
                                }
                                else
                                {
                                    <a class="nav-link " asp-area="" asp-controller="Job" asp-action="Material">Settings</a>
                                }
                            }

                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@


        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PrecisionToolingEF/Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - Plaid Pug Software - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

PrecisionToolingEF/Views/Shared/_JobEditLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Precision Tooling EF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrecisionToolingEF.styles.css" asp-append-version="true" />
    <title>Precision Tools & Manufacturing Solutions</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    
</head>
<body>
    <partial name="_MainHeader" />

    
    <div class="container">

        <partial name="_JobNavigationView" />

        @* <!--  JOB NAVIGATION -->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav nav-tabs">

                        <li class="nav-item">
                            @{
                                if(ViewData["Screen"]?.ToString() == "General")
                                {
                                    <a class="nav-link active" asp-area="" asp-controller="Job" asp-action="JobGeneral">General Information</a>
                                }
                                else
                                {
                                    <a class="nav-link" asp-area="" asp-controller="Job" asp-action="JobGeneral">General Information</a>
                                }
                            }
                            
                        </li>
                        <li class="nav-item">
                            @{
                                if(ViewData["Screen"]?.ToString() == "Labor")
                                {
                                    <a class="nav-link active" asp-area="" asp-controller="Job" asp-action="Labor">Labor</a>
                                }
                                else
                                {
                                    <a class="nav-link " asp-area="" asp-controller="Job" asp-action="Labor">Labor</a>
                                }
                            }
                            
                        </li>
                        <li class="nav-item">
                            @{
                                if (ViewData["Screen"]?.ToString() == "Material")
                                {
                                    <a class="nav-link active" asp-area="" asp-controller="Job" asp-action="Material">Material</a>
                                }
                                else
                                {
                                    <a class="nav-link " asp-area="" asp-controller="Job" asp-action="Material">Material</a>
                                }
                            }
                            
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
    
    
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PrecisionToolingEF/Views/Shared/_JobNavigationView.cshtml
<!--  JOB NAVIGATION -->
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">

        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="nav nav-pills">

                <li class="nav-item">
                    @{
                        if (ViewData["Screen"]?.ToString() == "General")
                        {
                            <a class="nav-link active" asp-area="" asp-controller="Job" asp-action="JobGeneral">General Information</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-area="" asp-controller="Job" asp-action="JobGeneral">General Information</a>
                        }
                    }

                </li>
                <li class="nav-item">
                    @{
                        if (ViewData["Screen"]?.ToString() == "Labor")
                        {
                            <a class="nav-link active" asp-area="" asp-controller="Job" asp-action="Labor">Labor</a>
                        }
                        else
                        {
                            <a class="nav-link " asp-area="" asp-controller="Job" asp-action="Labor">Labor</a>
                        }
                    }

                </li>
                <li class="nav-item">
                    @{
                        if (ViewData["Screen"]?.ToString() == "Material")
                        {
                            <a class="nav-link active" asp-area="" asp-controller="Job" asp-action="Material">Material</a>
                        }
                        else
                        {
                            <a class="nav-link " asp-area="" asp-controller="Job" asp-action="Material">Material</a>
                        }
                    }

                </li>
            </ul>
        </div>
    </div>
</nav>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

PrecisionToolingEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Precision Tooling EF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrecisionToolingEF.styles.css" asp-append-version="true" />
    <title>Precision Tools & Manufacturing Solutions</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    
</head>
<body>

    <partial name="_MainHeader"/>
    @* <header>
       
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrecisionToolingEF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Administration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="Index">Jobs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />
    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Plaid Pug Software - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PrecisionToolingEF/Views/Shared/_MainHeader.cshtml
<header>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Precision Tooling EF</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="Index">Administration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="Index">Jobs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@